# Generated by Django 4.1.6 on 2023-02-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('anons', models.CharField(max_length=250, verbose_name='Anons')),
                ('full_text', models.TextField(verbose_name='Full text')),
                ('date', models.DateTimeField(verbose_name='Publication date')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('capitalization', models.IntegerField(verbose_name='Capitalization')),
                ('ceo_id', models.ManyToManyField(to='main.director')),
            ],
            options={
                'verbose_name': 'Firm',
                'verbose_name_plural': 'Firms',
            },
        ),
        migrations.CreateModel(
            name='ShopQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness', models.IntegerField(verbose_name='Cleanliness')),
                ('staff_courtesy', models.IntegerField(verbose_name='Staff courtesy')),
                ('products_quality', models.IntegerField(verbose_name='Products quality')),
            ],
            options={
                'verbose_name': 'ShopQuality',
                'verbose_name_plural': 'ShopsQualities',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('employees_number', models.IntegerField(verbose_name='Employees number')),
                ('shop_quality_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.shopquality')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('cost', models.IntegerField(verbose_name='Cost')),
                ('firm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.firm')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='last_acquired_firm_id',
            field=models.ManyToManyField(to='main.firm'),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Date and time')),
                ('cost', models.IntegerField(verbose_name='Cost')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
            },
        ),
    ]
