# Generated by Django 4.1.6 on 2023-02-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_file', models.FileField(upload_to='courses_files')),
                ('file_name', models.CharField(max_length=100, verbose_name='File name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
            options={
                'verbose_name': 'Course file',
                'verbose_name_plural': 'Course files',
            },
        ),
    ]
