# Generated by Django 4.1.6 on 2023-02-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firm',
            old_name='ceo_id',
            new_name='directors',
        ),
        migrations.RemoveField(
            model_name='director',
            name='last_acquired_firm_id',
        ),
    ]
