# Generated by Django 4.1.6 on 2023-02-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='course',
            field=models.ManyToManyField(to='main.course'),
        ),
    ]
