# Generated by Django 4.1.6 on 2023-02-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_author_id_alter_course_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('MONDAY', 'Понедельник'), ('TUESDAY', 'Вторник'), ('WEDNESDAY', 'Среда'), ('THURSDAY', 'Четверг'), ('FRIDAY', 'Пятница'), ('SATURDAY', 'Суббота'), ('SUNDAY', 'Воскресенье')], default='MONDAY', max_length=12)),
                ('subject', models.TextField(verbose_name='Subject')),
                ('time_start', models.TimeField(verbose_name='Start Time')),
                ('time_end', models.TimeField(verbose_name='End Time')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
