# Generated by Django 4.1.6 on 2023-02-10 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_ceo_id_firm_directors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('text', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.AlterField(
            model_name='check',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 1, 1), verbose_name='Date and time'),
        ),
    ]
