# Generated by Django 4.1.6 on 2023-02-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_announcement_alter_check_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
