# Generated by Django 4.1.6 on 2023-02-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_scheduleevent_alter_check_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleevent',
            name='date',
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
