# Generated by Django 4.1.6 on 2023-02-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.TextField(default='Лылова А.В.', verbose_name='Teacher'),
            preserve_default=False,
        ),
    ]
