# Generated by Django 4.1.6 on 2023-02-10 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_alter_check_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(default=datetime.date(1, 1, 1), verbose_name='Date'),
        ),
    ]
