# Generated by Django 4.1.6 on 2023-02-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_announcement_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, verbose_name='Login')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('bio', models.CharField(max_length=300, verbose_name='Bio')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Avatar')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
