# Generated by Django 4.1.6 on 2023-02-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_courseprogress'),
        ('main', '0005_timetable_building_room'),
    ]

    operations = [
    ]
