# Generated by Django 4.1.6 on 2023-02-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profileinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='avatar',
            field=models.ImageField(upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
